name: Deploy Web Application using ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: rhel

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Copy files to RHEL Web Server
        uses: appleboy/ssh-action@1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
             cd /root/claud-ai/day3/actions
             git pull 
             docker compose up -d --build
