name: Generate 3rd Party Library

on:
  push:
    branches:
      - master

jobs:
  generate-3rd-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7

      - name: hold your breath , script is going to run
        run: |
           for i in {1..10}; do
            echo "sleeping for $i seconds" && sleep 1
           done
      - name: Run generate script
        run: bash bash.sh
