name: Multi Jobs

on:
  push:
    branches:
      - master # or main

jobs:
  job-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install cowsay
        run: | 
          sudo apt-get update
          sudo apt-get install -y cowsay

      - name: Run cowsay build
        run: /usr/games/cowsay -f elephant "I'm an elephant" >> elephant.txt

      # 1. Upload elephant.txt as an artifact
      - name: Upload elephant artifact
        uses: actions/upload-artifact@v4
        with:
          name: elephant-file
          path: elephant.txt

  job-test:
    needs: job-build
    name: Test
    runs-on: ubuntu-latest
    steps:
      # 2. Download the artifact in job-test
      - name: Download elephant artifact
        uses: actions/download-artifact@v4
        with:
          name: elephant-file

      - name: Run sleep
        run: |
          for i in {1..10}; do
            echo "Job 2 sleeping for $i seconds" && sleep 1
          done

      - name: check elephant.txt
        run: ls -l elephant.txt

  job-deploy:
    needs: job-test
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # 3. Download the artifact in job-deploy
      - name: Download elephant artifact
        uses: actions/download-artifact@v4
        with:
          name: elephant-file

      - name: cat elephant.txt
        run: cat elephant.txt

      - name: deploy elephant
        run: echo "deploying elephant"