name: Testing github workflow

on: push

jobs:
  onest_github_action:
    runs-on: ubuntu-latest
    steps:
      - name: OS name
        run: cat /etc/os-release

      - name: date
        run: date

      - name: user
        run: id

      - name: This is all
        run: echo "this is all. done"
      - name:  sleeping 5
        run: sleep 5
      - name:  sleeping 10
        run: sleep 10
      - name:  checkout-repo
        uses: actions/checkout@v7